spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.homeright.home
      secretName: homeright-api-tls
  rules:
    - host: api.homeright.home
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: homeright-api
                port:
                  number: 8000