apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homeright-api
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.homeright.home
      secretName: homeright-api-tls
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: homeright-api
                port:
                  number: 8000

